// This is an autogenerated file from Firebase Studio.

import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "scanalyze-8x740",
  "appId": "1:213425288049:web:ae112fdb817ea9724b3cd0",
  "storageBucket": "scanalyze-8x740.firebasestorage.app",
  "apiKey": "AIzaSyBLmxDGCIyUAJgz8DkNjneKQXvScp0ea9Q",
  "authDomain": "scanalyze-8x740.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "213425288049"
};

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
